import type { Lang } from "./ui";

// Translation overlay for CMS (Sanity) content that is authored in English.
// Keyed by the trimmed English source string. This is an interim measure until
// the CMS itself is localized; keep entries in sync if the Sanity text changes.
// Draft NL/DE — please review.
export const cmsTranslations: Record<string, { nl: string; de: string }> = {
	// --- service titles ---
	"Integrated Innovation Trials": {
		nl: "Geïntegreerde innovatieproeven",
		de: "Integrierte Innovationsversuche",
	},
	"Supply Chain Optimization & Emission Reduction": {
		nl: "Optimalisatie van de toeleveringsketen & emissiereductie",
		de: "Lieferkettenoptimierung & Emissionsreduktion",
	},
	"Digital Twin Research Platform": {
		nl: "Digital-twin-onderzoeksplatform",
		de: "Digital-Twin-Forschungsplattform",
	},
	// --- service short descriptions ---
	"Validate feed innovations, emission-reduction technologies, and efficiency solutions inside a fully integrated, commercial-scale poultry chain. Generate the third-party validated evidence your customers and regulators require.": {
		nl: "Valideer voerinnovaties, emissiereducerende technologieën en efficiëntieoplossingen binnen een volledig geïntegreerde pluimveeketen op commerciële schaal. Genereer het door derden gevalideerde bewijs dat uw klanten en toezichthouders vereisen.",
		de: "Validieren Sie Futterinnovationen, emissionsmindernde Technologien und Effizienzlösungen in einer vollständig integrierten Geflügelkette in kommerziellem Maßstab. Erzeugen Sie die von Dritten validierten Belege, die Ihre Kunden und Behörden verlangen.",
	},
	"Optimize your upstream supply chain to reduce total cost of purchase while simultaneously lowering CO₂ and NH₃ emissions. Decision-ready insights aligned with CSRD, Scope 3, and retailer reporting requirements.": {
		nl: "Optimaliseer uw upstream-toeleveringsketen om de totale inkoopkosten te verlagen en tegelijkertijd de CO₂- en NH₃-uitstoot te verminderen. Beslissingsklare inzichten die aansluiten op CSRD, Scope 3 en de rapportage-eisen van retailers.",
		de: "Optimieren Sie Ihre vorgelagerte Lieferkette, um die Gesamtbeschaffungskosten zu senken und gleichzeitig die CO₂- und NH₃-Emissionen zu reduzieren. Entscheidungsreife Erkenntnisse im Einklang mit CSRD, Scope 3 und den Berichtsanforderungen des Handels.",
	},
	"A fully instrumented digital twin of the complete poultry production chain, designed for academic and applied research on production efficiency, animal welfare, and sustainability.": {
		nl: "Een volledig uitgeruste digital twin van de complete pluimveeproductieketen, ontworpen voor academisch en toegepast onderzoek naar productie-efficiëntie, dierenwelzijn en duurzaamheid.",
		de: "Ein vollständig instrumentierter digitaler Zwilling der gesamten Geflügelproduktionskette, konzipiert für akademische und angewandte Forschung zu Produktionseffizienz, Tierwohl und Nachhaltigkeit.",
	},
	// --- service features ---
	"Controlled trials in a commercial-scale production environment": {
		nl: "Gecontroleerde proeven in een productieomgeving op commerciële schaal",
		de: "Kontrollierte Versuche in einer Produktionsumgebung in kommerziellem Maßstab",
	},
	"Full-cycle data capture across feed, health, emissions, and performance": {
		nl: "Dataregistratie over de hele cyclus voor voer, gezondheid, emissies en prestaties",
		de: "Datenerfassung über den gesamten Zyklus für Futter, Gesundheit, Emissionen und Leistung",
	},
	"Independent third-party validation of results": {
		nl: "Onafhankelijke validatie van resultaten door derden",
		de: "Unabhängige Validierung der Ergebnisse durch Dritte",
	},
	"Benchmarking against established industry baselines": {
		nl: "Benchmarking ten opzichte van gevestigde branchenormen",
		de: "Benchmarking gegenüber etablierten Branchen-Benchmarks",
	},
	"Structured pathway from pilot validation to commercial deployment": {
		nl: "Gestructureerd traject van pilotvalidatie tot commerciële uitrol",
		de: "Strukturierter Weg von der Pilotvalidierung bis zum kommerziellen Einsatz",
	},
	"End-to-end upstream supply chain mapping": {
		nl: "End-to-end in kaart brengen van de upstream-toeleveringsketen",
		de: "End-to-End-Kartierung der vorgelagerten Lieferkette",
	},
	"Scenario modeling for cost, CO₂, and NH₃ outcomes": {
		nl: "Scenariomodellering voor kosten-, CO₂- en NH₃-uitkomsten",
		de: "Szenariomodellierung für Kosten-, CO₂- und NH₃-Ergebnisse",
	},
	"Quantified emission footprints per supplier and production stage": {
		nl: "Gekwantificeerde emissievoetafdrukken per leverancier en productiefase",
		de: "Quantifizierte Emissions-Fußabdrücke pro Lieferant und Produktionsstufe",
	},
	"Alignment with CSRD, GHG Protocol, and SBTi frameworks": {
		nl: "Afstemming op CSRD-, GHG Protocol- en SBTi-kaders",
		de: "Ausrichtung an CSRD, GHG Protocol und SBTi-Rahmenwerken",
	},
	"Strategic sourcing and procurement recommendations": {
		nl: "Strategische sourcing- en inkoopaanbevelingen",
		de: "Strategische Beschaffungs- und Einkaufsempfehlungen",
	},
	"Continuous data access across the full production chain": {
		nl: "Continue datatoegang over de hele productieketen",
		de: "Kontinuierlicher Datenzugriff über die gesamte Produktionskette",
	},
	"Real-time monitoring with comprehensive historical archives": {
		nl: "Realtime monitoring met uitgebreide historische archieven",
		de: "Echtzeit-Monitoring mit umfassenden historischen Archiven",
	},
	"Support for multi-stage and longitudinal study designs": {
		nl: "Ondersteuning voor meerfasige en longitudinale onderzoeksopzetten",
		de: "Unterstützung für mehrstufige und longitudinale Studiendesigns",
	},
	"Publication-ready datasets with documented methodology": {
		nl: "Publicatieklare datasets met gedocumenteerde methodologie",
		de: "Publikationsreife Datensätze mit dokumentierter Methodik",
	},
	"Open science principles and reproducibility standards": {
		nl: "Open-science-principes en reproduceerbaarheidsnormen",
		de: "Open-Science-Prinzipien und Reproduzierbarkeitsstandards",
	},
	// --- advantage (why-us stat) titles ---
	"Conplete broiler value chain integration": {
		nl: "Volledige integratie van de vleeskuikenketen",
		de: "Vollständige Integration der Broiler-Wertschöpfungskette",
	},
	"Independent third party validation": {
		nl: "Onafhankelijke validatie door derden",
		de: "Unabhängige Validierung durch Dritte",
	},
	"Digital twin technology": {
		nl: "Digital-twin-technologie",
		de: "Digital-Twin-Technologie",
	},
	"Real-time data analysis": {
		nl: "Realtime data-analyse",
		de: "Echtzeit-Datenanalyse",
	},
	// --- research project titles ---
	"Controlled Intervention Trials for Feed Additives, Housing Technologies, and Management Practices": {
		nl: "Gecontroleerde interventieproeven voor voeradditieven, huisvestingstechnologieën en managementpraktijken",
		de: "Kontrollierte Interventionsversuche für Futterzusatzstoffe, Haltungstechnologien und Managementpraktiken",
	},
	"Full-Chain Efficiency Benchmarking in Commercial Broiler Production": {
		nl: "Efficiëntiebenchmarking van de hele keten in de commerciële vleeskuikenproductie",
		de: "Effizienz-Benchmarking der gesamten Kette in der kommerziellen Broilerproduktion",
	},
	"Carbon Footprint Measurement Across the Broiler Production Chain": {
		nl: "Meting van de CO₂-voetafdruk in de vleeskuikenproductieketen",
		de: "Messung des CO₂-Fußabdrucks entlang der Broiler-Produktionskette",
	},
	"NH3 Emission Quantification and Mitigation in Broiler Housing Systems": {
		nl: "Kwantificering en reductie van NH₃-emissies in vleeskuikenstalsystemen",
		de: "Quantifizierung und Minderung von NH₃-Emissionen in Broiler-Haltungssystemen",
	},
	// --- research project summaries ---
	"A structured trial environment for evaluating the performance, welfare, and environmental impact of new feed additives, housing technologies, and management practices under commercial-scale production conditions.": {
		nl: "Een gestructureerde proefomgeving voor het evalueren van de prestaties, het welzijn en de milieu-impact van nieuwe voeradditieven, huisvestingstechnologieën en managementpraktijken onder productieomstandigheden op commerciële schaal.",
		de: "Eine strukturierte Versuchsumgebung zur Bewertung von Leistung, Tierwohl und Umweltwirkung neuer Futterzusatzstoffe, Haltungstechnologien und Managementpraktiken unter Produktionsbedingungen in kommerziellem Maßstab.",
	},
	"A comprehensive analysis of feed conversion ratios, growth performance, mortality, and operational efficiency across all stages of commercial broiler production, establishing validated benchmarks for the European poultry sector.": {
		nl: "Een uitgebreide analyse van voederconversies, groeiprestaties, uitval en operationele efficiëntie in alle fasen van de commerciële vleeskuikenproductie, met gevalideerde benchmarks voor de Europese pluimveesector.",
		de: "Eine umfassende Analyse von Futterverwertung, Wachstumsleistung, Mortalität und betrieblicher Effizienz über alle Stufen der kommerziellen Broilerproduktion, die validierte Benchmarks für den europäischen Geflügelsektor schafft.",
	},
	"Precise, continuous measurement of carbon emissions from breeding through processing, combined with impact assessment of targeted interventions on the total chain footprint.": {
		nl: "Nauwkeurige, continue meting van koolstofemissies van broederij tot verwerking, gecombineerd met een impactbeoordeling van gerichte ingrepen op de totale voetafdruk van de keten.",
		de: "Präzise, kontinuierliche Messung der Kohlenstoffemissionen von der Brüterei bis zur Verarbeitung, kombiniert mit einer Wirkungsbewertung gezielter Maßnahmen auf den Gesamt-Fußabdruck der Kette.",
	},
	"Advanced measurement of ammonia emissions across housing systems and management practices, supporting intervention effectiveness evaluation and compliance with NEC Directive and BBT/BAT requirements.": {
		nl: "Geavanceerde meting van ammoniakemissies over huisvestingssystemen en managementpraktijken, ter ondersteuning van de evaluatie van de effectiviteit van ingrepen en naleving van de NEC-richtlijn en BBT/BAT-eisen.",
		de: "Fortschrittliche Messung von Ammoniakemissionen über Haltungssysteme und Managementpraktiken hinweg, zur Bewertung der Wirksamkeit von Maßnahmen und zur Einhaltung der NEC-Richtlinie und der BVT/BAT-Anforderungen.",
	},

	// --- research project body paragraphs (dense technical text — review recommended) ---
	"Carbon accounting in poultry production has historically relied on annualized estimates and emission factors derived from generic models. While useful for high-level reporting, this approach is poorly suited to evaluating the real-time impact of operational decisions or assessing the effectiveness of specific mitigation interventions.": {
		nl: "Koolstofboekhouding in de pluimveeproductie steunde historisch op gejaarlijkte schattingen en emissiefactoren afgeleid van generieke modellen. Hoewel nuttig voor rapportage op hoofdlijnen, is deze aanpak slecht geschikt om de realtime impact van operationele beslissingen te evalueren of de effectiviteit van specifieke reductiemaatregelen te beoordelen.",
		de: "Die CO₂-Bilanzierung in der Geflügelproduktion stützte sich historisch auf jährliche Schätzungen und Emissionsfaktoren aus generischen Modellen. Für die Berichterstattung auf hoher Ebene nützlich, eignet sich dieser Ansatz jedoch schlecht, um die Echtzeitwirkung betrieblicher Entscheidungen zu bewerten oder die Wirksamkeit spezifischer Minderungsmaßnahmen zu beurteilen.",
	},
	"This project implements continuous CO₂ measurement infrastructure across each stage of the broiler production chain, from breeder operations through grow-out, transport, and processing. Direct measurement is combined with activity-based modeling to attribute emissions to specific operational variables — feed sourcing, energy use, housing conditions, and logistics.": {
		nl: "Dit project implementeert een infrastructuur voor continue CO₂-meting in elke fase van de vleeskuikenketen, van vermeerdering via opfok tot transport en verwerking. Directe meting wordt gecombineerd met activiteitsgebaseerde modellering om emissies toe te wijzen aan specifieke operationele variabelen — voerinkoop, energieverbruik, huisvestingsomstandigheden en logistiek.",
		de: "Dieses Projekt implementiert eine Infrastruktur zur kontinuierlichen CO₂-Messung über jede Stufe der Broiler-Produktionskette hinweg, von der Elterntierhaltung über die Mast bis zu Transport und Verarbeitung. Die Direktmessung wird mit aktivitätsbasierter Modellierung kombiniert, um Emissionen spezifischen betrieblichen Variablen zuzuordnen — Futterbezug, Energieverbrauch, Haltungsbedingungen und Logistik.",
	},
	"The data layer generated supports both granular intervention impact assessment and aggregated chain-level reporting aligned with CSRD, GHG Protocol, and SBTi frameworks. Project outputs will contribute to refining emission factors used across the European poultry sector.": {
		nl: "De gegenereerde datalaag ondersteunt zowel een gedetailleerde beoordeling van de impact van ingrepen als geaggregeerde rapportage op ketenniveau in lijn met CSRD-, GHG Protocol- en SBTi-kaders. De projectresultaten dragen bij aan het verfijnen van emissiefactoren die in de Europese pluimveesector worden gebruikt.",
		de: "Die erzeugte Datenschicht unterstützt sowohl die granulare Bewertung der Wirkung von Maßnahmen als auch die aggregierte Berichterstattung auf Kettenebene im Einklang mit CSRD, GHG Protocol und SBTi-Rahmenwerken. Die Projektergebnisse tragen zur Verfeinerung der im europäischen Geflügelsektor verwendeten Emissionsfaktoren bei.",
	},
	"The pace of innovation in poultry production — feed additives, precision housing technologies, alternative protein sources, welfare-oriented management practices — has accelerated significantly. However, the gap between promising laboratory results and validated commercial performance remains a barrier to adoption, particularly where multiple performance dimensions must be evaluated simultaneously.": {
		nl: "Het innovatietempo in de pluimveeproductie — voeradditieven, precisiehuisvestingstechnologieën, alternatieve eiwitbronnen, welzijnsgerichte managementpraktijken — is aanzienlijk versneld. De kloof tussen veelbelovende laboratoriumresultaten en gevalideerde commerciële prestaties blijft echter een drempel voor adoptie, vooral wanneer meerdere prestatiedimensies tegelijk moeten worden geëvalueerd.",
		de: "Das Innovationstempo in der Geflügelproduktion — Futterzusatzstoffe, Präzisionshaltungstechnologien, alternative Proteinquellen, tierwohlorientierte Managementpraktiken — hat sich erheblich beschleunigt. Die Lücke zwischen vielversprechenden Laborergebnissen und validierter kommerzieller Leistung bleibt jedoch ein Hindernis für die Einführung, insbesondere wenn mehrere Leistungsdimensionen gleichzeitig bewertet werden müssen.",
	},
	"This project provides a standardized intervention testing environment in which new technologies and practices are evaluated under commercial-scale production conditions, with parallel measurement of production performance, animal welfare indicators, emission profiles, and economic outcomes. Trial design follows established protocols for controlled comparison, with independent validation of methodology and results.": {
		nl: "Dit project biedt een gestandaardiseerde testomgeving voor ingrepen waarin nieuwe technologieën en werkwijzen worden geëvalueerd onder productieomstandigheden op commerciële schaal, met parallelle meting van productieprestaties, dierenwelzijnsindicatoren, emissieprofielen en economische uitkomsten. De proefopzet volgt gevestigde protocollen voor gecontroleerde vergelijking, met onafhankelijke validatie van methodologie en resultaten.",
		de: "Dieses Projekt bietet eine standardisierte Testumgebung für Maßnahmen, in der neue Technologien und Praktiken unter Produktionsbedingungen in kommerziellem Maßstab bewertet werden, mit paralleler Messung von Produktionsleistung, Tierwohlindikatoren, Emissionsprofilen und wirtschaftlichen Ergebnissen. Das Versuchsdesign folgt etablierten Protokollen für den kontrollierten Vergleich, mit unabhängiger Validierung von Methodik und Ergebnissen.",
	},
	"Outputs support evidence-based adoption decisions by producers, integrators, retailers, and regulatory bodies, and provide innovators with market-ready validation packages aligned with EU regulatory and commercial requirements.": {
		nl: "De resultaten ondersteunen op bewijs gebaseerde adoptiebeslissingen door producenten, integrators, retailers en toezichthouders, en bieden innovators marktklare validatiepakketten die aansluiten op EU-regelgeving en commerciële eisen.",
		de: "Die Ergebnisse unterstützen evidenzbasierte Einführungsentscheidungen von Produzenten, Integratoren, Handel und Regulierungsbehörden und liefern Innovatoren marktreife Validierungspakete im Einklang mit EU-regulatorischen und kommerziellen Anforderungen.",
	},
	"Operational efficiency in poultry production is shaped by hundreds of interacting variables — genetics, feed composition, housing, climate management, flock health, and processing conditions. Most efficiency studies isolate one or two of these factors, leaving the systemic interactions unmeasured and the resulting benchmarks incomplete.": {
		nl: "Operationele efficiëntie in de pluimveeproductie wordt bepaald door honderden op elkaar inwerkende variabelen — genetica, voersamenstelling, huisvesting, klimaatbeheer, koppelgezondheid en verwerkingsomstandigheden. De meeste efficiëntiestudies isoleren een of twee van deze factoren, waardoor de systemische interacties ongemeten blijven en de resulterende benchmarks onvolledig zijn.",
		de: "Die betriebliche Effizienz in der Geflügelproduktion wird von Hunderten zusammenwirkenden Variablen geprägt — Genetik, Futterzusammensetzung, Haltung, Klimamanagement, Herdengesundheit und Verarbeitungsbedingungen. Die meisten Effizienzstudien isolieren einen oder zwei dieser Faktoren, sodass die systemischen Wechselwirkungen ungemessen bleiben und die resultierenden Benchmarks unvollständig sind.",
	},
	"This project establishes a full-chain efficiency framework by capturing continuous performance data across breeder, grow-out, transport, and processing stages. Feed conversion ratios, daily weight gain, mortality patterns, uniformity, and processing yields are measured under standardized conditions, with each data point traceable to its production context.": {
		nl: "Dit project brengt een efficiëntiekader voor de hele keten tot stand door continue prestatiegegevens vast te leggen over de fasen vermeerdering, opfok, transport en verwerking. Voederconversies, dagelijkse groei, uitvalpatronen, uniformiteit en verwerkingsrendementen worden onder gestandaardiseerde omstandigheden gemeten, waarbij elk datapunt herleidbaar is tot de productiecontext.",
		de: "Dieses Projekt etabliert ein Effizienzrahmenwerk für die gesamte Kette, indem kontinuierliche Leistungsdaten über die Stufen Elterntierhaltung, Mast, Transport und Verarbeitung erfasst werden. Futterverwertung, tägliche Gewichtszunahme, Mortalitätsmuster, Uniformität und Verarbeitungsausbeuten werden unter standardisierten Bedingungen gemessen, wobei jeder Datenpunkt auf seinen Produktionskontext zurückführbar ist.",
	},
	"The outcome is a set of validated efficiency benchmarks that account for the full production system, providing reference values for producers, integrators, and policy bodies working on sustainable intensification of poultry production.": {
		nl: "Het resultaat is een set gevalideerde efficiëntiebenchmarks die rekening houden met het volledige productiesysteem en referentiewaarden bieden voor producenten, integrators en beleidsinstanties die werken aan duurzame intensivering van de pluimveeproductie.",
		de: "Das Ergebnis ist ein Satz validierter Effizienz-Benchmarks, die das gesamte Produktionssystem berücksichtigen und Referenzwerte für Produzenten, Integratoren und politische Gremien liefern, die an einer nachhaltigen Intensivierung der Geflügelproduktion arbeiten.",
	},
	"Ammonia emissions from poultry housing remain one of the most regulated and contested environmental impacts of the sector. Compliance with the EU National Emission Ceilings Directive, national emission policies, and Best Available Techniques (BAT) reference documents requires accurate, defensible measurement — yet many operations still rely on estimated values derived from outdated emission factors.": {
		nl: "Ammoniakemissies uit pluimveestallen blijven een van de meest gereguleerde en betwiste milieu-impacts van de sector. Naleving van de EU-richtlijn nationale emissieplafonds, nationaal emissiebeleid en referentiedocumenten voor Beste Beschikbare Technieken (BBT) vereist nauwkeurige, verdedigbare meting — toch steunen veel bedrijven nog op geschatte waarden afgeleid van verouderde emissiefactoren.",
		de: "Ammoniakemissionen aus der Geflügelhaltung bleiben eine der am stärksten regulierten und umstrittensten Umweltwirkungen der Branche. Die Einhaltung der EU-Richtlinie über nationale Emissionshöchstmengen, nationaler Emissionsvorschriften und der Referenzdokumente zu den besten verfügbaren Techniken (BVT) erfordert genaue, belastbare Messungen — doch viele Betriebe stützen sich noch auf Schätzwerte aus veralteten Emissionsfaktoren.",
	},
	"This project applies advanced ammonia measurement systems across multiple housing configurations and management practices, quantifying NH₃ emission patterns under varying ventilation, litter, feed, and stocking conditions. The methodology supports both research-grade emission characterization and operational guidance for producers seeking compliance with regulatory frameworks.": {
		nl: "Dit project past geavanceerde ammoniakmeetsystemen toe op meerdere huisvestingsconfiguraties en managementpraktijken en kwantificeert NH₃-emissiepatronen onder wisselende ventilatie-, strooisel-, voer- en bezettingsomstandigheden. De methodologie ondersteunt zowel emissiekarakterisering op onderzoeksniveau als operationele richtlijnen voor producenten die willen voldoen aan regelgevende kaders.",
		de: "Dieses Projekt setzt fortschrittliche Ammoniakmesssysteme über mehrere Haltungskonfigurationen und Managementpraktiken hinweg ein und quantifiziert NH₃-Emissionsmuster unter wechselnden Lüftungs-, Einstreu-, Futter- und Besatzbedingungen. Die Methodik unterstützt sowohl die Emissionscharakterisierung auf Forschungsniveau als auch operative Leitlinien für Produzenten, die die Einhaltung regulatorischer Rahmenwerke anstreben.",
	},
	"Intervention effectiveness is evaluated through controlled comparative trials, generating evidence on mitigation technologies, feed adjustments, and management practices that deliver verifiable NH₃ reductions without compromising animal welfare or production performance.": {
		nl: "De effectiviteit van ingrepen wordt geëvalueerd via gecontroleerde vergelijkende proeven, die bewijs opleveren over reductietechnologieën, voeraanpassingen en managementpraktijken die verifieerbare NH₃-reducties opleveren zonder afbreuk te doen aan dierenwelzijn of productieprestaties.",
		de: "Die Wirksamkeit der Maßnahmen wird durch kontrollierte Vergleichsversuche bewertet, die Belege zu Minderungstechnologien, Futteranpassungen und Managementpraktiken liefern, die überprüfbare NH₃-Reduktionen erzielen, ohne Tierwohl oder Produktionsleistung zu beeinträchtigen.",
	},
	// --- innovations (names / short / descriptions) + labels ---
	"Family heat / heat recovery": { nl: "Familiewarmte / warmteterugwinning", de: "Familienwärme / Wärmerückgewinnung" },
	"Family heat": { nl: "Familiewarmte", de: "Familienwärme" },
	"Recovers residual heat to warm the houses, cutting natural-gas use and CO₂.": { nl: "Wint restwarmte terug om de stallen te verwarmen, wat het aardgasverbruik en CO₂ vermindert.", de: "Gewinnt Restwärme zurück, um die Ställe zu heizen, und senkt so Erdgasverbrauch und CO₂." },
	"Bioenergy plant — Renure production": { nl: "Bio-energiecentrale — Renure-productie", de: "Bioenergieanlage — Renure-Produktion" },
	"Renure": { nl: "Renure", de: "Renure" },
	"Refines digestate into a renewable fertiliser, recovering nitrogen and displacing fossil products.": { nl: "Verwerkt digestaat tot een hernieuwbare meststof, wint stikstof terug en vervangt fossiele producten.", de: "Veredelt Gärrest zu einem erneuerbaren Dünger, gewinnt Stickstoff zurück und ersetzt fossile Produkte." },
	"Own feed program": { nl: "Eigen voerprogramma", de: "Eigenes Futterprogramm" },
	"Own feed": { nl: "Eigen voer", de: "Eigenes Futter" },
	"An in-house feed programme giving full control over ingredients, quality and traceability.": { nl: "Een eigen voerprogramma met volledige controle over ingrediënten, kwaliteit en traceerbaarheid.", de: "Ein eigenes Futterprogramm mit voller Kontrolle über Zutaten, Qualität und Rückverfolgbarkeit." },
	"Vaccine development": { nl: "Vaccinontwikkeling", de: "Impfstoffentwicklung" },
	"Vaccine": { nl: "Vaccin", de: "Impfstoff" },
	"Vaccines tailored to the flock's real disease pressure, reducing medical intervention.": { nl: "Vaccins afgestemd op de werkelijke ziektedruk van het koppel, wat medisch ingrijpen vermindert.", de: "Impfstoffe, die auf den tatsächlichen Krankheitsdruck der Herde abgestimmt sind und medizinische Eingriffe reduzieren." },
	"Solar panels on the production site": { nl: "Zonnepanelen op de productielocatie", de: "Solaranlagen am Produktionsstandort" },
	"Solar panels": { nl: "Zonnepanelen", de: "Solaranlagen" },
	"On-site solar covering much of the operation's electricity, displacing grid power.": { nl: "Zonne-energie op locatie die een groot deel van de elektriciteit dekt en netstroom vervangt.", de: "Solarstrom vor Ort, der einen Großteil des Strombedarfs deckt und Netzstrom ersetzt." },
	"Short chain — avoided transport kilometres": { nl: "Korte keten — vermeden transportkilometers", de: "Kurze Kette — vermiedene Transportkilometer" },
	"Short-chain transport": { nl: "Korteketen-transport", de: "Kurzketten-Transport" },
	"Production, processing and feed kept close together to avoid transport kilometres.": { nl: "Productie, verwerking en voer dicht bij elkaar om transportkilometers te vermijden.", de: "Produktion, Verarbeitung und Futter nah beieinander, um Transportkilometer zu vermeiden." },
	"Light recipe": { nl: "Lichtschema", de: "Lichtrezept" },
	"A researched lighting schedule matched to the birds' biology to support welfare.": { nl: "Een onderzocht lichtschema afgestemd op de biologie van de dieren om het welzijn te ondersteunen.", de: "Ein erforschtes Lichtprogramm, abgestimmt auf die Biologie der Tiere, um das Tierwohl zu fördern." },
	"Bioenergy plant — green gas production": { nl: "Bio-energiecentrale — groengasproductie", de: "Bioenergieanlage — Grüngasproduktion" },
	"Green gas": { nl: "Groen gas", de: "Grünes Gas" },
	"Upgrades biogas to grid-quality green gas, turning manure streams into renewable energy.": { nl: "Waardeert biogas op tot groen gas van netkwaliteit en zet meststromen om in hernieuwbare energie.", de: "Bereitet Biogas zu Grüngas in Netzqualität auf und macht aus Gülleströmen erneuerbare Energie." },
	"Air scrubber": { nl: "Luchtwasser", de: "Abluftwäscher" },
	"Scrubs house exhaust air of ammonia, dust and odour before it leaves the site.": { nl: "Reinigt de uitgaande stallucht van ammoniak, stof en geur voordat deze de locatie verlaat.", de: "Reinigt die Abluft der Ställe von Ammoniak, Staub und Geruch, bevor sie den Standort verlässt." },
	"Short chain — avoided cross-contamination risk": { nl: "Korte keten — vermeden kruisbesmettingsrisico", de: "Kurze Kette — vermiedenes Kreuzkontaminationsrisiko" },
	"Short-chain biosecurity": { nl: "Korteketen-bioveiligheid", de: "Kurzketten-Biosicherheit" },
	"A short, controlled chain that minimises cross-contamination risk between farms.": { nl: "Een korte, gecontroleerde keten die het risico op kruisbesmetting tussen bedrijven minimaliseert.", de: "Eine kurze, kontrollierte Kette, die das Kreuzkontaminationsrisiko zwischen Betrieben minimiert." },
	"Veterinary analysis development": { nl: "Ontwikkeling van veterinaire analyse", de: "Entwicklung veterinärmedizinischer Analytik" },
	"Vet. analysis": { nl: "Vet. analyse", de: "Vet.-Analytik" },
	"In-house veterinary diagnostics that catch health signals early.": { nl: "Eigen veterinaire diagnostiek die gezondheidssignalen vroeg opvangt.", de: "Eigene veterinärmedizinische Diagnostik, die Gesundheitssignale früh erkennt." },
	"Water treatment that keeps drinking lines clean and cuts contaminated discharge.": { nl: "Waterbehandeling die drinkwaterleidingen schoon houdt en verontreinigde lozing vermindert.", de: "Wasseraufbereitung, die Tränkeleitungen sauber hält und kontaminierte Abwässer reduziert." },
	"Fire-suppression technology": { nl: "Brandblustechnologie", de: "Brandbekämpfungstechnologie" },
	"Fire suppression": { nl: "Brandbestrijding", de: "Brandbekämpfung" },
	"Advanced fire-detection and suppression protecting birds, staff and buildings.": { nl: "Geavanceerde branddetectie en -bestrijding die dieren, medewerkers en gebouwen beschermt.", de: "Fortschrittliche Branderkennung und -bekämpfung, die Tiere, Mitarbeiter und Gebäude schützt." },
	"AI-driven broiler behaviour recognition": { nl: "AI-gestuurde herkenning van vleeskuikengedrag", de: "KI-gestützte Erkennung des Broilerverhaltens" },
	"AI behaviour": { nl: "AI-gedrag", de: "KI-Verhalten" },
	"Computer-vision AI that reads broiler behaviour to flag stress and illness early.": { nl: "Computer-vision-AI die het gedrag van vleeskuikens leest om stress en ziekte vroeg te signaleren.", de: "Computer-Vision-KI, die das Verhalten von Broilern liest, um Stress und Krankheit früh zu erkennen." },
	"Bioenergy plant — N₂ stripper (digestate)": { nl: "Bio-energiecentrale — N₂-stripper (digestaat)", de: "Bioenergieanlage — N₂-Stripper (Gärrest)" },
	"N₂ stripper": { nl: "N₂-stripper", de: "N₂-Stripper" },
	"Recovers ammonia-nitrogen from digestate as a usable product instead of an emission.": { nl: "Wint ammoniakstikstof uit digestaat terug als bruikbaar product in plaats van als emissie.", de: "Gewinnt Ammoniak-Stickstoff aus Gärrest als nutzbares Produkt zurück statt als Emission." },
	"Bioenergy plant — WaterSafe": { nl: "Bio-energiecentrale — WaterSafe", de: "Bioenergieanlage — WaterSafe" },
	"Bio-WaterSafe": { nl: "Bio-WaterSafe", de: "Bio-WaterSafe" },
	"WaterSafe integrated with the bioenergy plant, cleaning process water and recovering resources.": { nl: "WaterSafe geïntegreerd met de bio-energiecentrale, die proceswater reinigt en grondstoffen terugwint.", de: "WaterSafe integriert in die Bioenergieanlage, reinigt Prozesswasser und gewinnt Ressourcen zurück." },
	"Vaccination method development": { nl: "Ontwikkeling van vaccinatiemethoden", de: "Entwicklung von Impfmethoden" },
	"Vacc. method": { nl: "Vacc.-methode", de: "Impfmethode" },
	"More precise, lower-stress ways of administering vaccines to the birds.": { nl: "Nauwkeurigere, stressarmere manieren om de dieren te vaccineren.", de: "Präzisere, stressärmere Methoden, die Tiere zu impfen." },
	"Food safety — zero antibiotics use": { nl: "Voedselveiligheid — nul antibioticagebruik", de: "Lebensmittelsicherheit — kein Antibiotikaeinsatz" },
	"Zero antibiotics": { nl: "Nul antibiotica", de: "Kein Antibiotikum" },
	"Raising the flock with zero routine antibiotics — the top of the system.": { nl: "Het koppel opfokken zonder routinematig antibioticagebruik — de top van het systeem.", de: "Aufzucht der Herde ohne routinemäßige Antibiotika — die Spitze des Systems." },
	"Welfare & health dashboard": { nl: "Welzijns- en gezondheidsdashboard", de: "Tierwohl- und Gesundheits-Dashboard" },
	"Welfare dashboard": { nl: "Welzijnsdashboard", de: "Tierwohl-Dashboard" },
	"A live dashboard pulling every sensor and analysis into one welfare picture.": { nl: "Een live dashboard dat elke sensor en analyse samenbrengt in één welzijnsbeeld.", de: "Ein Live-Dashboard, das jeden Sensor und jede Analyse zu einem Tierwohl-Gesamtbild zusammenführt." },
	"Environmental safety — NH₃ / particulates / odour": { nl: "Milieuveiligheid — NH₃ / fijnstof / geur", de: "Umweltsicherheit — NH₃ / Feinstaub / Geruch" },
	"Environmental NH₃": { nl: "Milieu-NH₃", de: "Umwelt-NH₃" },
	"Managing ammonia, dust and odour at the site boundary to protect the surroundings.": { nl: "Beheer van ammoniak, stof en geur aan de terreingrens om de omgeving te beschermen.", de: "Management von Ammoniak, Staub und Geruch an der Standortgrenze zum Schutz der Umgebung." },
	"Rooster management": { nl: "Haanmanagement", de: "Hahnenmanagement" },
	"Rooster mgmt": { nl: "Haanbeheer", de: "Hahnenmanagement" },
	"Careful rooster management supporting flock balance, behaviour and welfare.": { nl: "Zorgvuldig haanmanagement dat de balans, het gedrag en het welzijn van het koppel ondersteunt.", de: "Sorgfältiges Hahnenmanagement, das Gleichgewicht, Verhalten und Wohl der Herde unterstützt." },
	"Emissions": { nl: "Emissies", de: "Emissionen" },
	"Production": { nl: "Productie", de: "Produktion" },
	"Health & Welfare": { nl: "Gezondheid & welzijn", de: "Gesundheit & Tierwohl" },
	"Safety": { nl: "Veiligheid", de: "Sicherheit" },
	"Electricity": { nl: "Elektriciteit", de: "Strom" },
	"Water discharge": { nl: "Waterlozing", de: "Wasserableitung" },
	"Nutrient retention": { nl: "Nutriëntenbehoud", de: "Nährstoffrückhalt" },
	"required": { nl: "vereist", de: "erforderlich" },
	"enhancing": { nl: "versterkend", de: "verstärkend" },
	// --- innovation detailed explanations (details) ---
	"Broiler houses need a great deal of heat, especially early in each cycle when young chicks cannot yet regulate their own body temperature. Rather than burning gas for it, this system recovers residual heat from the on-site bioenergy plant and surrounding processes and feeds it back into the houses. Heat that would otherwise be wasted becomes the primary source of warmth for the flock, delivering a large and measurable reduction in natural-gas use and the associated CO₂. Because heating is one of the biggest energy demands in poultry production, closing this loop turns a running cost into an efficiency gain — and every cubic metre of gas left unburned is emissions that never reach the atmosphere.": { nl: "Vleeskuikenstallen hebben veel warmte nodig, vooral vroeg in elke ronde wanneer jonge kuikens hun eigen lichaamstemperatuur nog niet kunnen regelen. In plaats van daarvoor gas te verbranden, wint dit systeem restwarmte terug uit de bio-energiecentrale op locatie en uit omliggende processen en voert die terug naar de stallen. Warmte die anders verloren zou gaan, wordt de belangrijkste warmtebron voor het koppel en levert een grote, meetbare vermindering van het aardgasverbruik en de bijbehorende CO₂ op. Omdat verwarming een van de grootste energievragers in de pluimveehouderij is, verandert het sluiten van deze kringloop een lopende kostenpost in een efficiëntiewinst — en elke kubieke meter gas die niet wordt verbrand, is uitstoot die de atmosfeer nooit bereikt.", de: "Broilerställe benötigen viel Wärme, besonders früh in jedem Durchgang, wenn die jungen Küken ihre Körpertemperatur noch nicht selbst regulieren können. Statt dafür Gas zu verbrennen, gewinnt dieses System Restwärme aus der Bioenergieanlage vor Ort und den umliegenden Prozessen zurück und führt sie in die Ställe zurück. Wärme, die sonst verloren ginge, wird zur Hauptwärmequelle für die Herde und bringt eine große, messbare Senkung des Erdgasverbrauchs und des damit verbundenen CO₂. Da die Heizung einer der größten Energieverbraucher in der Geflügelhaltung ist, verwandelt das Schließen dieses Kreislaufs laufende Kosten in einen Effizienzgewinn — und jeder nicht verbrannte Kubikmeter Gas ist Ausstoß, der die Atmosphäre nie erreicht." },
	"Digestate from the bioenergy plant still holds valuable nitrogen, which is normally lost or becomes an emission problem. Instead of treating it as waste, the Renure process refines it into a renewable mineral fertiliser that can replace fossil-based products. This keeps nutrients circulating within the system, recovers nitrogen that would otherwise escape, and reduces the operation's dependence on externally produced fertiliser. It is a clear example of the site's circular thinking: an output stream from one process becomes a valuable input for another, cutting both waste and purchased inputs at the same time.": { nl: "Digestaat uit de bio-energiecentrale bevat nog waardevolle stikstof, die normaal verloren gaat of een emissieprobleem wordt. In plaats van het als afval te behandelen, verfijnt het Renure-proces het tot een hernieuwbare minerale meststof die fossiele producten kan vervangen. Zo blijven nutriënten binnen het systeem circuleren, wordt stikstof teruggewonnen die anders zou ontsnappen en vermindert de afhankelijkheid van extern geproduceerde kunstmest. Het is een duidelijk voorbeeld van het circulaire denken op de locatie: een uitgaande stroom van het ene proces wordt een waardevolle input voor het andere, waardoor tegelijk zowel afval als aangekochte inputs worden verminderd.", de: "Der Gärrest aus der Bioenergieanlage enthält noch wertvollen Stickstoff, der normalerweise verloren geht oder zum Emissionsproblem wird. Statt ihn als Abfall zu behandeln, veredelt ihn der Renure-Prozess zu einem erneuerbaren Mineraldünger, der fossile Produkte ersetzen kann. So bleiben Nährstoffe im System im Kreislauf, wird Stickstoff zurückgewonnen, der sonst entweichen würde, und die Abhängigkeit von extern erzeugtem Dünger sinkt. Es ist ein klares Beispiel für das zirkuläre Denken am Standort: Der Ausgangsstrom eines Prozesses wird zum wertvollen Eingangsstoff eines anderen und verringert so zugleich Abfall und zugekaufte Betriebsmittel." },
	"A tailored, in-house feed programme gives full control over what the birds eat — ingredients, quality, and traceability from source to trough. Because feed drives growth, gut condition and overall health, this programme is the foundation many other innovations rely on, from antibiotic-free rearing to the welfare data captured elsewhere in the system. Owning the recipe means the operation can respond quickly to what the flock actually needs, rather than accepting a fixed off-the-shelf formulation. It is one of the most connected innovations on the site precisely because everything downstream — health, welfare, food safety — starts with the bird's diet.": { nl: "Een op maat gemaakt, eigen voerprogramma geeft volledige controle over wat de dieren eten — ingrediënten, kwaliteit en traceerbaarheid van bron tot voerbak. Omdat voer de groei, darmconditie en algehele gezondheid bepaalt, is dit programma de basis waarop veel andere innovaties steunen, van antibioticavrij opfokken tot de welzijnsdata die elders in het systeem worden verzameld. Het bezit van het recept betekent dat de onderneming snel kan inspelen op wat het koppel werkelijk nodig heeft, in plaats van een vaste kant-en-klare formule te accepteren. Het is een van de meest verbonden innovaties op de locatie, juist omdat alles verderop — gezondheid, welzijn, voedselveiligheid — begint bij het dieet van het dier.", de: "Ein maßgeschneidertes, eigenes Futterprogramm gibt volle Kontrolle darüber, was die Tiere fressen — Zutaten, Qualität und Rückverfolgbarkeit von der Quelle bis zum Trog. Da Futter Wachstum, Darmgesundheit und allgemeine Gesundheit bestimmt, ist dieses Programm die Grundlage, auf die sich viele andere Innovationen stützen, von der antibiotikafreien Aufzucht bis zu den Tierwohldaten, die anderswo im System erfasst werden. Das eigene Rezept bedeutet, dass der Betrieb schnell auf das reagieren kann, was die Herde tatsächlich braucht, statt eine feste Standardrezeptur hinzunehmen. Es ist eine der am stärksten vernetzten Innovationen am Standort, gerade weil alles Nachgelagerte — Gesundheit, Tierwohl, Lebensmittelsicherheit — mit der Ernährung des Tieres beginnt." },
	"Developing vaccines matched to the flock's actual disease pressure means birds are protected against the threats that matter on this specific site, rather than a generic national profile. Better-targeted immunity keeps birds healthier through the cycle and reduces the need for medical intervention later. It is a cornerstone of raising birds without routine antibiotics: if the flock is well protected from the start, the whole chain of health and food-safety measures becomes achievable. This work feeds directly into vaccination-method development and the welfare dashboard, so protection and monitoring advance together.": { nl: "Het ontwikkelen van vaccins die zijn afgestemd op de werkelijke ziektedruk van het koppel betekent dat de dieren worden beschermd tegen de dreigingen die er op deze specifieke locatie toe doen, in plaats van tegen een algemeen landelijk profiel. Beter gerichte immuniteit houdt de dieren de hele ronde gezonder en vermindert de behoefte aan medisch ingrijpen later. Het is een hoeksteen van het opfokken van dieren zonder routinematig antibioticagebruik: als het koppel vanaf het begin goed beschermd is, wordt de hele keten van gezondheids- en voedselveiligheidsmaatregelen haalbaar. Dit werk sluit direct aan op de ontwikkeling van vaccinatiemethoden en het welzijnsdashboard, zodat bescherming en monitoring samen vooruitgaan.", de: "Impfstoffe zu entwickeln, die auf den tatsächlichen Krankheitsdruck der Herde abgestimmt sind, bedeutet, dass die Tiere gegen die Bedrohungen geschützt werden, die an diesem konkreten Standort zählen, statt gegen ein allgemeines nationales Profil. Besser gezielte Immunität hält die Tiere über den gesamten Durchgang gesünder und verringert später den Bedarf an medizinischen Eingriffen. Es ist ein Eckpfeiler der Aufzucht ohne routinemäßige Antibiotika: Ist die Herde von Anfang an gut geschützt, wird die gesamte Kette der Gesundheits- und Lebensmittelsicherheitsmaßnahmen erreichbar. Diese Arbeit fließt direkt in die Entwicklung von Impfmethoden und das Tierwohl-Dashboard ein, sodass Schutz und Überwachung gemeinsam vorankommen." },
	"A large on-site solar array generates a substantial share of the electricity the operation consumes, directly displacing grid power and its emissions. Combined with the bioenergy plant, it moves the site toward producing more of its own clean energy than it draws from outside. Self-generated power also cushions the operation against volatile energy prices and grid constraints, which is increasingly important for energy-intensive facilities. The electricity it provides is what makes power-hungry innovations such as the air scrubber and water treatment viable without simply shifting emissions onto the grid.": { nl: "Een groot zonnepark op de locatie wekt een aanzienlijk deel van de elektriciteit op die de onderneming verbruikt, waardoor netstroom en de bijbehorende uitstoot rechtstreeks worden vervangen. In combinatie met de bio-energiecentrale beweegt de locatie zich naar het zelf produceren van meer schone energie dan ze van buitenaf betrekt. Zelf opgewekte stroom beschermt de onderneming ook tegen volatiele energieprijzen en netbeperkingen, wat steeds belangrijker wordt voor energie-intensieve faciliteiten. De elektriciteit die het levert, is wat stroomintensieve innovaties zoals de luchtwasser en waterbehandeling haalbaar maakt zonder de uitstoot simpelweg naar het net te verschuiven.", de: "Eine große Solaranlage am Standort erzeugt einen erheblichen Teil des Stroms, den der Betrieb verbraucht, und ersetzt so direkt Netzstrom und dessen Emissionen. Zusammen mit der Bioenergieanlage bewegt sich der Standort dahin, mehr eigene saubere Energie zu erzeugen, als er von außen bezieht. Selbst erzeugter Strom schützt den Betrieb zudem vor volatilen Energiepreisen und Netzengpässen, was für energieintensive Anlagen zunehmend wichtig ist. Der bereitgestellte Strom macht stromhungrige Innovationen wie den Abluftwäscher und die Wasseraufbereitung erst möglich, ohne die Emissionen einfach auf das Netz zu verlagern." },
	"By keeping production, processing, and feed supply physically close together, the operation avoids a significant number of transport kilometres. Fewer kilometres means lower road emissions, lower cost per bird, and less handling — a simple structural choice with benefits that compound across the whole system. Short transport distances also mean birds and products spend less time in transit, which supports both welfare and quality. It is a decision made once at the level of how the site is organised, but it pays off in every single cycle thereafter.": { nl: "Door productie, verwerking en voervoorziening fysiek dicht bij elkaar te houden, vermijdt de onderneming een aanzienlijk aantal transportkilometers. Minder kilometers betekent lagere wegemissies, lagere kosten per dier en minder handling — een eenvoudige structurele keuze met voordelen die zich over het hele systeem opstapelen. Korte transportafstanden betekenen ook dat dieren en producten minder tijd onderweg zijn, wat zowel het welzijn als de kwaliteit ten goede komt. Het is een beslissing die één keer wordt genomen op het niveau van hoe de locatie is georganiseerd, maar die zich daarna in elke afzonderlijke ronde uitbetaalt.", de: "Indem Produktion, Verarbeitung und Futterversorgung räumlich nah beieinander bleiben, vermeidet der Betrieb eine erhebliche Zahl an Transportkilometern. Weniger Kilometer bedeuten geringere Straßenemissionen, niedrigere Kosten je Tier und weniger Handling — eine einfache strukturelle Entscheidung, deren Vorteile sich über das gesamte System summieren. Kurze Transportwege bedeuten auch, dass Tiere und Produkte weniger Zeit unterwegs sind, was sowohl dem Tierwohl als auch der Qualität zugutekommt. Es ist eine Entscheidung, die einmal auf der Ebene der Standortorganisation getroffen wird, sich aber danach in jedem einzelnen Durchgang auszahlt." },
	"Light has a profound effect on how broilers rest, feed, and behave. A researched lighting schedule — intensity, colour, and timing tuned to the birds' biology — supports natural day-night rhythms, calmer behaviour, and better welfare. Well-rested, low-stress birds are healthier and more resilient, which reduces the risk of problems that would otherwise call for intervention. The lighting programme works hand in hand with the behaviour-recognition AI and the welfare dashboard: the light shapes behaviour, and the monitoring confirms the flock is responding as intended.": { nl: "Licht heeft een diepgaand effect op hoe vleeskuikens rusten, eten en zich gedragen. Een onderzocht lichtschema — intensiteit, kleur en timing afgestemd op de biologie van de dieren — ondersteunt natuurlijke dag-nachtritmes, rustiger gedrag en beter welzijn. Goed uitgeruste, stressarme dieren zijn gezonder en veerkrachtiger, wat het risico op problemen vermindert die anders om ingrijpen zouden vragen. Het lichtprogramma werkt hand in hand met de gedragsherkennings-AI en het welzijnsdashboard: het licht vormt het gedrag, en de monitoring bevestigt dat het koppel reageert zoals bedoeld.", de: "Licht hat einen tiefgreifenden Einfluss darauf, wie Broiler ruhen, fressen und sich verhalten. Ein erforschtes Lichtprogramm — Intensität, Farbe und Timing, abgestimmt auf die Biologie der Tiere — unterstützt natürliche Tag-Nacht-Rhythmen, ruhigeres Verhalten und besseres Tierwohl. Gut ausgeruhte, stressarme Tiere sind gesünder und widerstandsfähiger, was das Risiko von Problemen senkt, die sonst einen Eingriff erfordern würden. Das Lichtprogramm arbeitet Hand in Hand mit der Verhaltenserkennungs-KI und dem Tierwohl-Dashboard: Das Licht formt das Verhalten, und die Überwachung bestätigt, dass die Herde wie beabsichtigt reagiert." },
	"The bioenergy plant digests manure and organic streams and upgrades the resulting biogas to grid-quality green gas. This turns a waste and emissions problem into renewable energy, displacing a large volume of fossil gas and delivering the single largest CO₂ reduction in the whole system. Because it sits at the heart of the site's circular design, the plant also feeds several other innovations: its residual heat warms the houses, its digestate becomes fertiliser, and its nitrogen is recovered rather than emitted. In other words, green gas is not just an energy product — it is the engine that makes much of the site's resource recovery possible.": { nl: "De bio-energiecentrale vergist mest en organische stromen en waardeert het resulterende biogas op tot groen gas van netkwaliteit. Dit verandert een afval- en emissieprobleem in hernieuwbare energie, verdringt een groot volume fossiel gas en levert de grootste enkele CO₂-reductie in het hele systeem. Omdat ze in het hart van het circulaire ontwerp van de locatie staat, voedt de centrale ook diverse andere innovaties: haar restwarmte verwarmt de stallen, haar digestaat wordt meststof en haar stikstof wordt teruggewonnen in plaats van uitgestoten. Met andere woorden, groen gas is niet zomaar een energieproduct — het is de motor die veel van de grondstofterugwinning op de locatie mogelijk maakt.", de: "Die Bioenergieanlage vergärt Gülle und organische Ströme und bereitet das entstehende Biogas zu Grüngas in Netzqualität auf. Das verwandelt ein Abfall- und Emissionsproblem in erneuerbare Energie, verdrängt eine große Menge fossiles Gas und bringt die größte einzelne CO₂-Senkung im gesamten System. Da sie im Herzen des zirkulären Standortkonzepts steht, speist die Anlage auch mehrere andere Innovationen: Ihre Restwärme heizt die Ställe, ihr Gärrest wird zu Dünger und ihr Stickstoff wird zurückgewonnen statt ausgestoßen. Mit anderen Worten: Grüngas ist nicht nur ein Energieprodukt — es ist der Motor, der einen Großteil der Ressourcenrückgewinnung am Standort erst möglich macht." },
	"Air scrubbers treat the air leaving the houses, capturing ammonia, fine dust, and odour before it reaches the surroundings. Cleaner exhaust air comes at the cost of some extra electricity, but it removes a large mass of ammonia each year and is central to being a good neighbour to the area around the site. The nitrogen captured by the scrubber is not simply discarded — it links into the digestate and nitrogen-recovery systems, so a pollutant becomes a recoverable resource. This is why the scrubber shows a small energy cost in red but strong reductions in ammonia and retained nutrients in green: it trades a little power for a large environmental gain.": { nl: "Luchtwassers behandelen de lucht die de stallen verlaat en vangen ammoniak, fijnstof en geur op voordat die de omgeving bereikt. Schonere uitgaande lucht gaat ten koste van wat extra elektriciteit, maar verwijdert jaarlijks een grote massa ammoniak en is essentieel om een goede buur te zijn voor het gebied rond de locatie. De stikstof die door de wasser wordt afgevangen, wordt niet zomaar weggegooid — ze sluit aan op de digestaat- en stikstofterugwinningssystemen, zodat een verontreinigende stof een terugwinbare grondstof wordt. Daarom toont de wasser een kleine energiekost in het rood, maar sterke reducties in ammoniak en behouden nutriënten in het groen: hij ruilt een beetje stroom voor een grote milieuwinst.", de: "Abluftwäscher behandeln die aus den Ställen austretende Luft und fangen Ammoniak, Feinstaub und Geruch ab, bevor sie die Umgebung erreichen. Sauberere Abluft geht zulasten von etwas zusätzlichem Strom, entfernt aber jedes Jahr eine große Menge Ammoniak und ist entscheidend, um ein guter Nachbar für die Umgebung des Standorts zu sein. Der vom Wäscher aufgefangene Stickstoff wird nicht einfach verworfen — er ist mit den Gärrest- und Stickstoffrückgewinnungssystemen verknüpft, sodass aus einem Schadstoff eine rückgewinnbare Ressource wird. Deshalb zeigt der Wäscher einen kleinen Energieaufwand in Rot, aber starke Senkungen bei Ammoniak und zurückgehaltenen Nährstoffen in Grün: Er tauscht ein wenig Strom gegen einen großen Umweltgewinn." },
	"A short, tightly controlled chain minimises the number of contact points where disease can enter or spread between farms. Fewer transfers and less mixing means lower cross-contamination risk — a structural biosecurity advantage that directly supports antibiotic-free production. Every additional link in a supply chain is another opportunity for pathogens to move; by keeping the chain short and under its own control, the operation removes many of those opportunities entirely. This makes the health and food-safety goals far more achievable, because prevention at the structural level is always more reliable than treatment after the fact.": { nl: "Een korte, strak gecontroleerde keten minimaliseert het aantal contactpunten waar ziekte tussen bedrijven kan binnenkomen of zich verspreiden. Minder overdrachten en minder menging betekenen een lager kruisbesmettingsrisico — een structureel bioveiligheidsvoordeel dat antibioticavrije productie rechtstreeks ondersteunt. Elke extra schakel in een toeleveringsketen is een nieuwe kans voor ziekteverwekkers om zich te verplaatsen; door de keten kort en onder eigen beheer te houden, neemt de onderneming veel van die kansen volledig weg. Dit maakt de gezondheids- en voedselveiligheidsdoelen veel haalbaarder, omdat preventie op structureel niveau altijd betrouwbaarder is dan behandeling achteraf.", de: "Eine kurze, straff kontrollierte Kette minimiert die Zahl der Kontaktpunkte, an denen Krankheiten zwischen Betrieben eindringen oder sich ausbreiten können. Weniger Übergaben und weniger Vermischung bedeuten ein geringeres Kreuzkontaminationsrisiko — ein struktureller Biosicherheitsvorteil, der die antibiotikafreie Produktion direkt unterstützt. Jedes zusätzliche Glied in einer Lieferkette ist eine weitere Gelegenheit für Krankheitserreger, sich zu bewegen; indem die Kette kurz und unter eigener Kontrolle bleibt, beseitigt der Betrieb viele dieser Gelegenheiten vollständig. Das macht die Gesundheits- und Lebensmittelsicherheitsziele weit erreichbarer, denn Prävention auf struktureller Ebene ist stets zuverlässiger als Behandlung im Nachhinein." },
	"In-house veterinary diagnostics turn health monitoring from reactive to proactive. Early, on-site analysis catches emerging issues before they spread, and the findings feed directly into the welfare and health dashboard for faster, better-informed decisions. Having diagnostic capability on the site rather than waiting on external labs shortens the time between a first signal and a response — and in a live flock, that time matters. Combined with the behaviour AI and vaccination programme, it forms a layered health system where problems are anticipated rather than simply managed.": { nl: "Eigen veterinaire diagnostiek verandert gezondheidsmonitoring van reactief naar proactief. Vroege analyse op locatie vangt opkomende problemen op voordat ze zich verspreiden, en de bevindingen voeden rechtstreeks het welzijns- en gezondheidsdashboard voor snellere, beter onderbouwde beslissingen. Diagnostische capaciteit op de locatie hebben in plaats van te wachten op externe labs verkort de tijd tussen een eerste signaal en een reactie — en bij een levend koppel telt die tijd. In combinatie met de gedrags-AI en het vaccinatieprogramma vormt het een gelaagd gezondheidssysteem waarin problemen worden voorzien in plaats van simpelweg beheerd.", de: "Eigene veterinärmedizinische Diagnostik macht aus der Gesundheitsüberwachung ein proaktives statt reaktives Vorgehen. Frühe Analysen vor Ort erkennen aufkommende Probleme, bevor sie sich ausbreiten, und die Ergebnisse fließen direkt in das Tierwohl- und Gesundheits-Dashboard für schnellere, fundiertere Entscheidungen ein. Diagnostik am Standort statt Warten auf externe Labore verkürzt die Zeit zwischen erstem Signal und Reaktion — und bei einer lebenden Herde zählt diese Zeit. Zusammen mit der Verhaltens-KI und dem Impfprogramm bildet sie ein mehrschichtiges Gesundheitssystem, in dem Probleme vorweggenommen statt bloß verwaltet werden." },
	"WaterSafe keeps drinking-water lines clean and biologically stable, which protects bird health, and it reduces the volume of contaminated water discharged from the site. Clean drinking water is a basic but often underrated pillar of flock health: contaminated lines can undermine every other health measure. On the environmental side, treating water so that less of it leaves the site as polluted discharge reduces the operation's footprint on the surrounding land and waterways. It integrates closely with the bioenergy plant's water systems, so water management and energy production reinforce one another rather than competing.": { nl: "WaterSafe houdt de drinkwaterleidingen schoon en biologisch stabiel, wat de diergezondheid beschermt, en het vermindert de hoeveelheid verontreinigd water die van de locatie wordt geloosd. Schoon drinkwater is een basale maar vaak onderschatte pijler van de koppelgezondheid: vervuilde leidingen kunnen elke andere gezondheidsmaatregel ondermijnen. Aan de milieukant vermindert het behandelen van water zodat er minder als vervuilde lozing van de locatie vertrekt de voetafdruk van de onderneming op het omliggende land en de waterlopen. Het integreert nauw met de watersystemen van de bio-energiecentrale, zodat waterbeheer en energieproductie elkaar versterken in plaats van met elkaar te concurreren.", de: "WaterSafe hält die Tränkeleitungen sauber und biologisch stabil, was die Tiergesundheit schützt, und verringert die Menge an kontaminiertem Wasser, das vom Standort abgeleitet wird. Sauberes Trinkwasser ist eine grundlegende, aber oft unterschätzte Säule der Herdengesundheit: Verunreinigte Leitungen können jede andere Gesundheitsmaßnahme untergraben. Auf der Umweltseite verringert die Aufbereitung des Wassers, sodass weniger davon als belastetes Abwasser den Standort verlässt, den Fußabdruck des Betriebs auf das umliegende Land und die Gewässer. Es ist eng mit den Wassersystemen der Bioenergieanlage verzahnt, sodass Wassermanagement und Energieerzeugung sich gegenseitig verstärken, statt zu konkurrieren." },
	"Advanced fire-detection and suppression technology protects the most vulnerable part of any livestock operation: large numbers of animals housed together under one roof. Early detection and rapid response safeguard birds, staff, and buildings, and underpin the site's overall safety case. Fire is one of the highest-consequence risks in intensive housing, so investing in prevention and fast suppression is as much an animal-welfare measure as it is an asset-protection one. It sits alongside the environmental-safety systems as part of the operation's commitment to running a safe, responsible site.": { nl: "Geavanceerde branddetectie- en blustechnologie beschermt het meest kwetsbare deel van elke veehouderij: grote aantallen dieren die samen onder één dak worden gehouden. Vroege detectie en snelle respons beschermen dieren, medewerkers en gebouwen, en onderbouwen de algehele veiligheid van de locatie. Brand is een van de risico's met de hoogste gevolgen in intensieve huisvesting, dus investeren in preventie en snelle bestrijding is evenzeer een dierenwelzijnsmaatregel als een maatregel voor de bescherming van bezittingen. Het staat naast de milieuveiligheidssystemen als onderdeel van de inzet van de onderneming om een veilige, verantwoorde locatie te runnen.", de: "Fortschrittliche Branderkennungs- und Löschtechnik schützt den verletzlichsten Teil jedes Tierhaltungsbetriebs: große Tierzahlen, die gemeinsam unter einem Dach gehalten werden. Frühe Erkennung und schnelle Reaktion schützen Tiere, Mitarbeiter und Gebäude und untermauern die Gesamtsicherheit des Standorts. Feuer ist eines der folgenschwersten Risiken in der intensiven Haltung, daher ist die Investition in Prävention und schnelle Bekämpfung ebenso eine Tierwohl- wie eine Sachwertschutzmaßnahme. Sie steht neben den Umweltsicherheitssystemen als Teil des Engagements des Betriebs, einen sicheren, verantwortungsvollen Standort zu führen." },
	"Computer-vision AI watches the flock continuously, reading posture, movement, and distribution to spot the early signals of stress, illness, or welfare problems — often before they are visible to the human eye. It is the sensing layer that powers the welfare dashboard and much of the health system, turning thousands of subtle behavioural cues into actionable alerts. Unlike periodic manual checks, the AI never looks away, so subtle changes across the whole flock are caught the moment they begin. This early warning is what lets staff intervene gently and early, supporting welfare and reducing the need for heavier interventions later.": { nl: "Computer-vision-AI observeert het koppel continu en leest houding, beweging en spreiding om de vroege signalen van stress, ziekte of welzijnsproblemen op te sporen — vaak voordat ze zichtbaar zijn voor het menselijk oog. Het is de sensorlaag die het welzijnsdashboard en een groot deel van het gezondheidssysteem aandrijft, en die duizenden subtiele gedragssignalen omzet in bruikbare waarschuwingen. In tegenstelling tot periodieke handmatige controles kijkt de AI nooit weg, zodat subtiele veranderingen in het hele koppel worden opgemerkt op het moment dat ze beginnen. Deze vroege waarschuwing is wat medewerkers in staat stelt om zacht en vroeg in te grijpen, wat het welzijn ondersteunt en de behoefte aan zwaardere ingrepen later vermindert.", de: "Computer-Vision-KI beobachtet die Herde kontinuierlich und liest Haltung, Bewegung und Verteilung, um die frühen Anzeichen von Stress, Krankheit oder Tierwohlproblemen zu erkennen — oft bevor sie für das menschliche Auge sichtbar sind. Sie ist die Sensorschicht, die das Tierwohl-Dashboard und einen Großteil des Gesundheitssystems antreibt und Tausende subtiler Verhaltenssignale in umsetzbare Warnungen verwandelt. Anders als bei regelmäßigen manuellen Kontrollen schaut die KI nie weg, sodass subtile Veränderungen in der gesamten Herde in dem Moment erfasst werden, in dem sie beginnen. Diese Frühwarnung ermöglicht es dem Personal, sanft und früh einzugreifen, was das Tierwohl fördert und den Bedarf an stärkeren Eingriffen später verringert." },
	"A nitrogen stripper on the bioenergy plant pulls ammonia-nitrogen out of the digestate and captures it as a usable product. Nitrogen that would otherwise escape as an emission is recovered instead, cutting ammonia and keeping valuable nutrients in productive use. Nitrogen management is one of the defining environmental challenges in livestock farming, and recovering it at source is far more effective than trying to deal with it once it has dispersed. The stripped nitrogen connects into the Renure and fertiliser streams, so a potential pollutant is transformed into a marketable, renewable input.": { nl: "Een stikstofstripper op de bio-energiecentrale trekt ammoniakstikstof uit het digestaat en vangt die op als bruikbaar product. Stikstof die anders als emissie zou ontsnappen, wordt in plaats daarvan teruggewonnen, wat ammoniak vermindert en waardevolle nutriënten in productief gebruik houdt. Stikstofbeheer is een van de bepalende milieu-uitdagingen in de veehouderij, en het bij de bron terugwinnen is veel effectiever dan het proberen aan te pakken zodra het zich heeft verspreid. De gestripte stikstof sluit aan op de Renure- en meststofstromen, zodat een potentiële verontreiniger wordt omgezet in een verhandelbare, hernieuwbare input.", de: "Ein Stickstoffstripper an der Bioenergieanlage zieht Ammoniak-Stickstoff aus dem Gärrest und fängt ihn als nutzbares Produkt auf. Stickstoff, der sonst als Emission entweichen würde, wird stattdessen zurückgewonnen, was Ammoniak senkt und wertvolle Nährstoffe in produktivem Einsatz hält. Stickstoffmanagement ist eine der prägenden Umweltherausforderungen der Tierhaltung, und die Rückgewinnung an der Quelle ist weit wirksamer als der Versuch, ihn zu behandeln, sobald er sich verteilt hat. Der abgeschiedene Stickstoff fließt in die Renure- und Düngerströme ein, sodass aus einem potenziellen Schadstoff ein marktfähiger, erneuerbarer Rohstoff wird." },
	"Integrating WaterSafe treatment with the bioenergy plant cleans process water and recovers resources within the same loop. It reduces discharge and strengthens the circular link between water management and energy production on the site. By handling water treatment where the energy and nutrient streams already come together, the operation avoids duplicating infrastructure and captures value that would otherwise be lost. It is a good illustration of how tightly the site's emissions innovations are woven together: energy, water, and nutrients are managed as one connected system rather than separate problems.": { nl: "Het integreren van WaterSafe-behandeling met de bio-energiecentrale reinigt proceswater en wint grondstoffen terug binnen dezelfde kringloop. Het vermindert lozing en versterkt de circulaire koppeling tussen waterbeheer en energieproductie op de locatie. Door waterbehandeling uit te voeren waar de energie- en nutriëntenstromen al samenkomen, vermijdt de onderneming het dupliceren van infrastructuur en vangt ze waarde op die anders verloren zou gaan. Het is een goede illustratie van hoe nauw de emissie-innovaties van de locatie met elkaar zijn verweven: energie, water en nutriënten worden beheerd als één verbonden systeem in plaats van als afzonderlijke problemen.", de: "Die Integration der WaterSafe-Aufbereitung mit der Bioenergieanlage reinigt Prozesswasser und gewinnt Ressourcen innerhalb desselben Kreislaufs zurück. Sie verringert die Ableitung und stärkt die zirkuläre Verbindung zwischen Wassermanagement und Energieerzeugung am Standort. Indem die Wasseraufbereitung dort erfolgt, wo Energie- und Nährstoffströme bereits zusammenlaufen, vermeidet der Betrieb doppelte Infrastruktur und erfasst Wert, der sonst verloren ginge. Es ist ein gutes Beispiel dafür, wie eng die Emissionsinnovationen des Standorts miteinander verwoben sind: Energie, Wasser und Nährstoffe werden als ein verbundenes System statt als getrennte Probleme verwaltet." },
	"Beyond which vaccines are used, how they are administered matters. Developing more precise, lower-stress vaccination methods improves protection while reducing handling stress on the birds — another building block of antibiotic-free rearing. Poor administration can waste a good vaccine or stress the flock unnecessarily, so refining the method protects both the investment and the bird. This work advances alongside vaccine development and the light programme, so that immunity is delivered in a way that fits the birds' welfare rather than working against it.": { nl: "Naast welke vaccins worden gebruikt, doet ook de manier van toedienen ertoe. Het ontwikkelen van nauwkeurigere, stressarmere vaccinatiemethoden verbetert de bescherming en vermindert tegelijk de handlingstress voor de dieren — een andere bouwsteen van antibioticavrij opfokken. Slechte toediening kan een goed vaccin verspillen of het koppel onnodig stress bezorgen, dus het verfijnen van de methode beschermt zowel de investering als het dier. Dit werk gaat vooruit naast de vaccinontwikkeling en het lichtprogramma, zodat immuniteit wordt geleverd op een manier die past bij het welzijn van de dieren in plaats van ertegenin te werken.", de: "Neben der Frage, welche Impfstoffe verwendet werden, kommt es auch darauf an, wie sie verabreicht werden. Die Entwicklung präziserer, stressärmerer Impfmethoden verbessert den Schutz und verringert zugleich den Handlingstress für die Tiere — ein weiterer Baustein der antibiotikafreien Aufzucht. Schlechte Verabreichung kann einen guten Impfstoff verschwenden oder die Herde unnötig stressen, daher schützt die Verfeinerung der Methode sowohl die Investition als auch das Tier. Diese Arbeit schreitet neben der Impfstoffentwicklung und dem Lichtprogramm voran, sodass Immunität auf eine Weise vermittelt wird, die zum Tierwohl passt, statt ihm entgegenzuwirken." },
	"Raising a flock with zero routine antibiotics is only possible when everything else is right. This food-safety programme sits at the top of the system, depending on feed, biosecurity, vaccination, welfare monitoring, and light management all working together — which is why it connects to more innovations than any other. It is less a single technology than the outcome of the whole system functioning as designed: keep birds healthy by prevention, and the need for routine medication disappears. Achieving it is a strong signal of both animal welfare and food safety, and it is precisely the interconnection shown in this map that makes it realistic rather than aspirational.": { nl: "Een koppel opfokken zonder routinematig antibioticagebruik is alleen mogelijk wanneer al het andere klopt. Dit voedselveiligheidsprogramma staat aan de top van het systeem en is afhankelijk van voer, bioveiligheid, vaccinatie, welzijnsmonitoring en lichtbeheer die allemaal samenwerken — daarom verbindt het met meer innovaties dan welke andere ook. Het is minder één technologie dan de uitkomst van het hele systeem dat functioneert zoals ontworpen: houd dieren gezond door preventie, en de behoefte aan routinematige medicatie verdwijnt. Het bereiken ervan is een sterk signaal van zowel dierenwelzijn als voedselveiligheid, en het is juist de onderlinge verbondenheid die in deze kaart wordt getoond die het realistisch maakt in plaats van een streven.", de: "Eine Herde ohne routinemäßige Antibiotika aufzuziehen, ist nur möglich, wenn alles andere stimmt. Dieses Lebensmittelsicherheitsprogramm steht an der Spitze des Systems und hängt davon ab, dass Futter, Biosicherheit, Impfung, Tierwohlüberwachung und Lichtmanagement alle zusammenwirken — weshalb es mit mehr Innovationen verbunden ist als jede andere. Es ist weniger eine einzelne Technologie als das Ergebnis des gesamten Systems, das wie vorgesehen funktioniert: Halte die Tiere durch Prävention gesund, und der Bedarf an routinemäßiger Medikation verschwindet. Es zu erreichen ist ein starkes Zeichen für Tierwohl und Lebensmittelsicherheit zugleich, und gerade die in dieser Karte gezeigte Vernetzung macht es realistisch statt bloß erstrebenswert." },
	"The welfare and health dashboard brings every signal — AI behaviour analysis, veterinary findings, environmental readings — into a single, live picture. It turns scattered data into fast, informed decisions and is the hub that ties the health and welfare innovations together. Rather than asking staff to watch many separate systems, it presents one coherent view of how the flock is doing right now and where attention is needed. As the connecting point for the health cluster, it is what allows the operation to act on the whole picture, not just isolated readings — the difference between collecting data and actually managing welfare.": { nl: "Het welzijns- en gezondheidsdashboard brengt elk signaal — AI-gedragsanalyse, veterinaire bevindingen, milieumetingen — samen in één live beeld. Het zet verspreide data om in snelle, onderbouwde beslissingen en is de spil die de gezondheids- en welzijnsinnovaties met elkaar verbindt. In plaats van medewerkers veel afzonderlijke systemen te laten bewaken, presenteert het één samenhangend beeld van hoe het koppel er op dit moment voor staat en waar aandacht nodig is. Als het verbindingspunt voor het gezondheidscluster is het wat de onderneming in staat stelt te handelen op het volledige beeld, niet alleen op geïsoleerde metingen — het verschil tussen data verzamelen en welzijn daadwerkelijk beheren.", de: "Das Tierwohl- und Gesundheits-Dashboard führt jedes Signal — KI-Verhaltensanalyse, veterinärmedizinische Befunde, Umweltmesswerte — zu einem einzigen Live-Bild zusammen. Es verwandelt verstreute Daten in schnelle, fundierte Entscheidungen und ist die Drehscheibe, die die Gesundheits- und Tierwohlinnovationen miteinander verbindet. Statt das Personal viele getrennte Systeme überwachen zu lassen, präsentiert es eine kohärente Sicht darauf, wie es der Herde gerade geht und wo Aufmerksamkeit nötig ist. Als Verbindungspunkt des Gesundheitsclusters ermöglicht es dem Betrieb, auf das Gesamtbild zu reagieren, nicht nur auf isolierte Messwerte — der Unterschied zwischen dem Sammeln von Daten und dem tatsächlichen Managen des Tierwohls." },
	"Managing ammonia, fine dust, and odour at the site boundary keeps the operation compatible with its surroundings and compliant with environmental limits. It links tightly to the air scrubber, the bioenergy plant, and the short-chain choices that reduce emissions at source. Being a responsible neighbour is not only a regulatory requirement but also part of maintaining a long-term licence to operate in the region. By combining reduction at source with capture at the boundary, the operation addresses environmental impact from both directions rather than relying on a single line of defence.": { nl: "Het beheersen van ammoniak, fijnstof en geur aan de terreingrens houdt de onderneming verenigbaar met haar omgeving en in overeenstemming met de milieugrenzen. Het is nauw verbonden met de luchtwasser, de bio-energiecentrale en de korteketenkeuzes die de emissies bij de bron verminderen. Een verantwoorde buur zijn is niet alleen een wettelijke eis, maar ook onderdeel van het behouden van een langetermijnvergunning om in de regio te opereren. Door reductie bij de bron te combineren met afvang aan de grens, pakt de onderneming de milieu-impact vanuit twee richtingen aan in plaats van te vertrouwen op één verdedigingslinie.", de: "Das Management von Ammoniak, Feinstaub und Geruch an der Standortgrenze hält den Betrieb mit seiner Umgebung vereinbar und im Einklang mit den Umweltgrenzwerten. Es ist eng mit dem Abluftwäscher, der Bioenergieanlage und den Kurzketten-Entscheidungen verbunden, die Emissionen an der Quelle verringern. Ein verantwortungsvoller Nachbar zu sein, ist nicht nur eine gesetzliche Anforderung, sondern auch Teil des Erhalts einer langfristigen Betriebserlaubnis in der Region. Durch die Kombination von Reduktion an der Quelle mit Abscheidung an der Grenze geht der Betrieb die Umweltwirkung aus zwei Richtungen an, statt sich auf eine einzige Verteidigungslinie zu verlassen." },
	"Careful rooster management supports the balance, behaviour, and welfare of the flock as a whole. It works alongside light management and the broader welfare system to keep birds calm and healthy. Getting this balance right influences group dynamics and stress levels across the entire house, which in turn affects health outcomes. Though it is an indirect innovation with no standalone impact figure, it contributes to the calm, well-managed flock on which many of the health and food-safety goals quietly depend.": { nl: "Zorgvuldig haanmanagement ondersteunt de balans, het gedrag en het welzijn van het koppel als geheel. Het werkt samen met het lichtbeheer en het bredere welzijnssysteem om de dieren rustig en gezond te houden. Deze balans goed krijgen beïnvloedt de groepsdynamiek en het stressniveau in de hele stal, wat op zijn beurt de gezondheidsuitkomsten beïnvloedt. Hoewel het een indirecte innovatie is zonder eigen impactcijfer, draagt het bij aan het rustige, goed beheerde koppel waarop veel van de gezondheids- en voedselveiligheidsdoelen stilletjes steunen.", de: "Sorgfältiges Hahnenmanagement unterstützt das Gleichgewicht, das Verhalten und das Wohl der Herde als Ganzes. Es arbeitet mit dem Lichtmanagement und dem umfassenderen Tierwohlsystem zusammen, um die Tiere ruhig und gesund zu halten. Dieses Gleichgewicht richtig hinzubekommen, beeinflusst die Gruppendynamik und das Stressniveau im gesamten Stall, was wiederum die Gesundheitsergebnisse beeinflusst. Obwohl es eine indirekte Innovation ohne eigene Wirkungszahl ist, trägt es zu der ruhigen, gut geführten Herde bei, auf die sich viele der Gesundheits- und Lebensmittelsicherheitsziele still verlassen." },
	// --- team member roles ---
	"Former Director": { nl: "Voormalig directeur", de: "Ehemaliger Direktor" },
	"Director of Broilers Operation": { nl: "Directeur vleeskuikenbedrijf", de: "Direktor Broilerbetrieb" },
	"Director of Parent Stock Operation": { nl: "Directeur ouderdierenbedrijf", de: "Direktor Elterntierbetrieb" },
	"General Manager": { nl: "Algemeen directeur", de: "Geschäftsführer" },
};

/** Translate a CMS string via the overlay; returns the original if untranslated. */
export function translateCms(text: string | null | undefined, lang: Lang): string {
	if (!text) return text ?? "";
	if (lang === "en") return text;
	return cmsTranslations[text.trim()]?.[lang] ?? text;
}
